version: '3'
services:
  mongo-db:
    image: mongo
    ports:
    - "27017:27017"
  web:
    build: angular-app
    ports: 
    - "4200:4200"
    volumes:
    - ./angular-app:/app
    links:
    - node-server
    command: npm run start
  node-server:
    build: 
      context: node-app
    ports:
    - "3000:3000"
    environment:
      #Match the server name and ports for the mongo db container
      DB_SERVER_URL: "mongodb://mongo-db:27017/pithy-path"
    volumes:
    - ./node-app:/code
    links:
    - mongo-db
    command: npm run start
