FROM node
WORKDIR /app
COPY . .
EXPOSE 4200

RUN npm install
RUN npm install -g @angular/cli
#RUN npm i && npm run build

#FROM nginx:alpine
#WORKDIR /usr/share/nginx/html
#RUN rm -rf ./*
#COPY --from=builder /app/dist/angular-app .

#EXPOSE 80